### ISSUE TITLE
ulimit达到之后三分钟日志就把磁盘写满了

### ISSUE THREAD

**Issue by missuzhang** [open-falcon/hbs#3]
日志如下：
2015/11/04 02:13:12 rpc.go:32: listener accept fail: accept tcp [::]:6030: too many open files
2015/11/04 02:13:12 rpc.go:32: listener accept fail: accept tcp [::]:6030: too many open files
.......
.......
.......
2015/11/04 02:16:36 rpc.go:32: listener accept fail: accept tcp [::]:6030: too many open files

代码中 hbs/rpc/rpc.go的start方法。
continue 之前sleep一段时间可能会更好。
                conn, err := l.Accept()
                if err != nil {
                        log.Println("listener accept fail:", err)
                        continue

**Comment by laiwei** [comment]
https://github.com/open-falcon/hbs/pull/2

已经做了改进，thx
