### ISSUE TITLE
关于hbs和agent之间的rpc请求转发

### ISSUE THREAD

**Issue by hackstoic** [open-falcon/hbs#6]
你好。 我们准备部署open-falcon作为我们的监控系统。 目前遇到一个问题。 

我们是三层架构， A 层与B层网络互通， B层与C层网络互通， 但A层不能之间访问C层。 

根据各自权衡， HBS不方便放在B层。 HBS 放在C层，agent是放在A层上的 ， 如何实现agent到hbs之间的通信？

期待答复~~谢谢。

**Comment by laiwei** [comment]
https://github.com/open-falcon/hbs-proxy
